# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

on:
    push:
        branches:
            - master
    pull_request:

name: "Continuous Integration"

jobs:
    supported-versions-matrix:
        name: Supported Versions Matrix
        runs-on: ubuntu-latest
        outputs:
            version: ${{ steps.supported-versions-matrix.outputs.version }}
        steps:
            - uses: actions/checkout@v3
            - id: supported-versions-matrix
              uses: WyriHaximus/github-action-composer-php-versions-in-range@v1
    tests:
        name: "Unit Tests"
        runs-on: ${{ matrix.operating-system }}
        needs:
            - supported-versions-matrix
        strategy:
            fail-fast: false
            matrix:
                operating-system: [ubuntu-latest, windows-latest, macOS-latest]
                php: ${{ fromJson(needs.supported-versions-matrix.outputs.version) }}
        steps:
            - name: Set git to use LF
              run: |
                  git config --global core.autocrlf false
                  git config --global core.eol lf

            - name: Checkout
              uses: actions/checkout@v3

            - name: Install PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: pcov
                  extensions: intl, sodium, xsl

            - name: Install dependencies
              uses: ramsey/composer-install@v3

            - name: Run Grumphp
              run: vendor/bin/grumphp run

            - name: Send PSALM data
              run: vendor/bin/psalm --shepherd --stats src/
              continue-on-error: true
